headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[dev]
command = "npm run dev"
port = 3000.0
publish = "src"

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\attil\\OneDrive\\Área de Trabalho\\Sistemas\\Jupiara\\Financeiro\\src"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"

[build.environment]
NODE_VERSION = "18"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/manifest.json"

[headers.values]
Content-Type = "application/manifest+json"

[[headers]]
for = "/sw.js"

[headers.values]
Content-Type = "application/javascript"
Service-Worker-Allowed = "/"

[[headers]]
for = "/*.js"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*.css"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*.png"

[headers.values]
Cache-Control = "public, max-age=2592000"

[[headers]]
for = "/*.jpg"

[headers.values]
Cache-Control = "public, max-age=2592000"

[[headers]]
for = "/*.svg"

[headers.values]
Cache-Control = "public, max-age=2592000"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]